/**
  * Even Fibonacci numbers
  * Problem 2
  * Published on 19 October 2001 at 06:00 pm [Server Time]
  * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  *
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  */
#include "solution.h"
#include <stdio.h>

/* Note the datatype for this solution is not good enough. An int only guarantees 16-bits, which is not enough for this solution. */

static
void
print_solution
    (euler_solution *p_solution)
{
    unsigned long f0;
    unsigned long f1;
    unsigned long tmp;

    unsigned long sum = 0;

    for (f0 = 0, f1 = 1; f1 < 4000000; tmp = f1, f1 += f0, f0 = tmp)
    {
        if (!(f1 & 1))
        {
            printf("%lu\n",f1);
            sum += f1;
        }
    }

    printf("sum == %lu\n", sum);
}

void
solve00002
    (euler_solution *p_solution)
{
    p_solution->print_solution = print_solution;
}
